#!/usr/bin/env bash
# Bash script that transfer a file from our client to a server

# Function to display usage
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    display_usage
    exit 1
fi

# Assigning arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username"@"$server_ip":~/

# Check if scp was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error transferring file."
fi
