#!/usr/bin/env bash
# A bash script that installs nginx web server on a server

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Replace default index.html with custom content
echo "Hello World!" | sudo tee /var/www/html/index.html
# Restart nginx (not using systemctl)
service nginx restart

# Confirm nginx is listening on port 80
netstat -tuln | grep ':80' > /dev/null
if [ $? -eq 0 ]; then
    echo "Nginx is listening on port 80."
else
    echo "Nginx failed to start or listen on port 80."
fi
