#!/usr/bin/env bash
# Configure your Nginx server so that "/redirect_me"
# is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "48i\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
sudo service nginx restart