#!/usr/bin/env bash
# Displaying Fizz Buzz and FizzBuzz

for ((number=1; number <= 100; number++))
do
	if ((number % 3 == 0 && number % 5 == 0)); then
		echo "FizzBuzz"
	elif ((number % 5 == 0)); then
		echo "Buzz"
	elif ((number % 3 == 0)); then
		echo "Fizz"
	else
		echo "$number"
	fi
done
