#!/usr/bin/env bash
# Displaying Fizz Buzz and FizzBuzz

number=1

while [ $number -le 100 ];
do
	if [ $number % 3 -eq 0 && $number % 5 -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $number % 5 -eq 0 ]; then
		echo "Buzz"
	elif [ $number % 3 -eq 0 ]; then
		echo "Fizz"
	fi
	echo "$number"
	((number++))
done
