#!/usr/bin/env bash
# Dispaly Best school with bad and good luck stuff

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((counter++))
done
