#!/usr/bin/env bash
# This script will change the IP @ of localhost and facebook
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
# adding at the second line '8.8.8.8 facebook.com'
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
