#!/bin/env bash
# A bash script that generates an SSH key pair
ssh-keygen -t rsa -b 4096 -N betty -f school
# -t rsa: specifies the type of key to create
# -b 4096: specifies the number of bits in the key
# -N betty: provides a new passphrase
# -f school: specifies the file in which to store the key
# The public key is stored in school.pub
# The private key is stored in school